titleSeparator: "|"
titleAddition: 专业保温管道与隔热管托制造商
description: >-
  河北兴欧管道有限公司，专注保温管道、聚乙烯夹克管、隔热管托及管道配件制造，支持工程定制，广泛应用于供热、市政、化工与能源领域。
images:
  - favicon.ico
ogLocale: en_US
titleHome: Helmani Food
twitterSite: "@gethyas"
twitterCreator: "@henkverlinde"
schemaType: Organization
schemaName: Hyas
schemaAuthor: Henk Verlinde
schemaAuthorTwitter: "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn: "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub: "https://github.com/h-enk"
schemaLocale: en-US
schemaLogo: logo-hyas.png
schemaLogoWidth: 512
schemaLogoHeight: 512
schemaImage: hyas.png
schemaImageWidth: 1280
schemaImageHeight: 640
schemaTwitter: "https://twitter.com/gethyas"
schemaLinkedIn: ""
schemaGitHub: "https://github.com/h-enk/hyas"
themeColor: "#3ac58d"
landscapePhotoWidths:
  - 900
  - 800
  - 700
  - 600
  - 500
portraitPhotoWidths:
  - 800
  - 700
  - 600
  - 500
lqipWidth: 20x
smallLimit: "320"
imageResponsive: true
imageConvertTo: webp
imageImageSizes:
  - "480"
  - "720"
  - "1080"
  - "1280"
  - "1600"
  - "2048"
singleSize: false
imageAddClass: img-fluid lazyload blur-up
defaultImage: default-image.png
fillImage: 1280x720 Center
alert: false
alertDismissable: true
alertText: >-
  Deliver web projects 10x faster. <a class="alert-link"
  href="https://www.netlify.com/whitepaper/" target="_blank" rel="noopener">Get
  the free enterprise paper →</a>
blogPageURL: blog
contactLink: contact
copyright: All right reserved copyright © Helmani 2022
footerLogo: images/site-navigation/logo3-radius.png
footerContact:
  topTitle: 开启合作
  title: 携手客户，共创未来
  button: 联系我们
fabformURL: "https://fabform.io/f/JpTXRUa"
googleAnalytics: YOUR GOOGLE ANALYTICS CODE
logo: images/site-navigation/logo4-nobg.png
address:
  address: "河北省沧州市盐山县蒲洼工业区兴欧管道"
  email: 493497321@qq.com
  openingHours: 工作日：08:00 - 17:30
  phone: (+86) 187 3074 0000
map:
  enable: false
  APIkey: YOUR GOOGLE MAP API
  latitude: "23.7783741"
  longitude: "90.3746808"
  pinImage: images/pin.png
social:
  - icon: fa-weixin
    url: ""
    weight: 1
  - icon: fa-tiktok
    url: "https://www.facebook.com/"
    weight: 2

_template: parameters_template
