@baseUrl = http://localhost:3000/api
@scope = cars
@id = 5c4e72cfa16d73705fa89bce

### get list
GET {{baseUrl}}/{{scope}} HTTP/1.1
content-type: application/json

### get one by id
GET {{baseUrl}}/{{scope}}/{{id}} HTTP/1.1
content-type: application/json

### new
POST {{baseUrl}}/{{scope}} HTTP/1.1
content-type: application/json

{
  "title": "XSTR",
  "brand": "Tesla",
  "price": "32,000",
  "age": 2,
  "services": {
    "Tesla Hong Kong": "21/04/2016",
    "Tesla Shanghai": "21/08/2018"
  }
}

### update
PUT {{baseUrl}}/{{scope}}/{{id}} HTTP/1.1
content-type: application/json

{
  "title": "XSTR_update"
}

### delete
DELETE  {{baseUrl}}/{{scope}}/{{id}} HTTP/1.1
