# Generated by Django 2.0.8 on 2018-09-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
