version: "3.9"
services:
  api:
    # container_name: go_api
    build: .
    # ports:
    #   - "8080:8080"
  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 3000:8080
