# Generated by Django 2.2.2 on 2019-06-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190630_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='person',
            field=models.ForeignKey(help_text='名字', on_delete=django.db.models.deletion.CASCADE, to='project.People'),
        ),
    ]
