# Add this line OUTSIDE the server block (inside the http block context)
lua_shared_dict my_cache_pool 10m; # Allocates 10MB of shared memory

lua_shared_dict my_locks 1m; # Required memory pool for locks

# Allocate shared memory for tracking traffic speeds
lua_shared_dict my_limit_req_store 10m;

server {
    listen 8080;
    server_name localhost;

    # 关键：开发环境关闭 Lua 缓存，修改 lua 文件直接生效
    lua_code_cache off;
	# http 请求
	resolver 8.8.8.8 1.1.1.1 valid=30s;
	resolver_timeout 2s;

    location /test {
        default_type text/plain;
        content_by_lua_file /app/lua/test.lua;
    }
}
